package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import org.sim.services.entities.*;
import java.util.Date;

/**
 * Medicion generated by hbm2java
 */

public class MedicionDto  implements java.io.Serializable {


     private Integer idMedicion;
     private Libroreport libroreport;
     private Date fecha;
     private String descripcion;
     private String glucosa;
     private String dosis;
     private Float temperatura;

    public MedicionDto() {
    }

	
    public MedicionDto(Integer idMedicion, Libroreport libroreport, Date fecha) {
        this.idMedicion = idMedicion;
        this.libroreport = libroreport;
        this.fecha = fecha;
    }
    public MedicionDto(Integer idMedicion, Libroreport libroreport, Date fecha, String descripcion) {
       this.idMedicion = idMedicion;
       this.libroreport = libroreport;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   

    public Integer getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(Integer idMedicion) {
        this.idMedicion = idMedicion;
    }

    public Libroreport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(Libroreport libroreport) {
        this.libroreport = libroreport;
    }


    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the glucosa
     */
    public String getGlucosa() {
        return glucosa;
    }

    /**
     * @param glucosa the glucosa to set
     */
    public void setGlucosa(String glucosa) {
        this.glucosa = glucosa;
    }

    /**
     * @return the dosis
     */
    public String getDosis() {
        return dosis;
    }

    /**
     * @param dosis the dosis to set
     */
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }

    /**
     * @return the temperatura
     */
    public Float getTemperatura() {
        return temperatura;
    }

    /**
     * @param temperatura the temperatura to set
     */
    public void setTemperatura(Float temperatura) {
        this.temperatura = temperatura;
    }




}


