package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import org.sim.services.entities.*;

/**
 * Nivelglucosa generated by hbm2java
 */

public class NivelglucosaDto extends CommonDto {
    


     private String glucosa;
     private String dosis;

    public NivelglucosaDto() {
    }

    public NivelglucosaDto( String glucosa, String dosis) {

       this.glucosa = glucosa;
       this.dosis = dosis;
    }
   
   
    public String getGlucosa() {
        return this.glucosa;
    }
    
    public void setGlucosa(String glucosa) {
        this.glucosa = glucosa;
    }

    
   
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }




}


