package org.sim.services.entities.dtos;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;


/**
 * Paciente generated by hbm2java
 */


public class PacienteListDto extends CommonDto implements java.io.Serializable {


   private List<PacienteDto> pacientesDto = new ArrayList();  

    /**
     * @return the pacientesDto
     */
    public List<PacienteDto> getPacientesDto() {
        return pacientesDto;
    }

    /**
     * @param pacientesDto the pacientesDto to set
     */
    public void setPacientesDto(List<PacienteDto> pacientesDto) {
        this.pacientesDto = pacientesDto;
    }

   
}


