package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

/**
 * Rol generated by hbm2java
 */

public class RolDto  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;


    public RolDto() {
    }

	
    public RolDto(int idRol) {
        this.idRol = idRol;
        //this.nombreRol = nombre;        
    }

  
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

}


