package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

/**
 * Temperatura generated by hbm2java
 */

public class TemperaturaDto extends CommonDto {


     private float temperatura;

    public TemperaturaDto() {
    }

    public TemperaturaDto(float temperatura) {
       this.temperatura = temperatura;
    }
     

    public float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(float temperatura) {
        this.temperatura = temperatura;
    }




}


