package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;


/**
 * Usuario generated by hbm2java
 */

public class UsuarioDto  implements java.io.Serializable {


     private Integer idUsuario;
     private RolDto rol;
     private int dni;
     private String nombre;
     private String usuario;
     private String password;
     private String mail;
     private Set<PacienteDto> pacientes = new HashSet<>();
     

    public UsuarioDto() {
    }

	/**
         * 
         * @param rol
         * @param dni
         * @param nombre 
         */
    
    public UsuarioDto(RolDto rol, int dni, String nombre) {
        this.rol = rol;
        this.dni = dni;
        this.nombre = nombre;
    }
    
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }


    public RolDto getRol() {
        return this.rol;
    }
    
    public void setRol(RolDto rol) {
        this.rol = rol;
    }

    
  
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }

    
  
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    
    public Set<PacienteDto> getPacientes() {
        return pacientes;
    }

    
    public void setPacientes(Set<PacienteDto> pacientes) {
        this.pacientes = pacientes;
    }

    /**
     * @return the mail
     */
    public String getMail() {
        return mail;
    }

    /**
     * @param mail the mail to set
     */
    public void setMail(String mail) {
        this.mail = mail;
    }
}


