package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

/**
 * Usuario generated by hbm2java
 */

public class UsuarioDto  implements java.io.Serializable {


     private Integer idUsuario;
     private RolDto rol;
     private int dni;
     private String nombre;
     

    public UsuarioDto() {
    }

	
    public UsuarioDto(RolDto rol, int dni, String nombre) {
        this.rol = rol;
        this.dni = dni;
        this.nombre = nombre;
    }
    
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }


    public RolDto getRol() {
        return this.rol;
    }
    
    public void setRol(RolDto rol) {
        this.rol = rol;
    }

    
  
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }

    
  
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}


