package org.sim.services.entities.dtos;
// Generated Oct 12, 2015 9:23:05 PM by Hibernate Tools 4.3.1

import org.sim.services.entities.*;
// Generated Oct 12, 2015 9:23:05 PM by Hibernate Tools 4.3.1



/**
 * Valorestemperatura generated by hbm2java
 */
public class ValoresMedicionDto extends CommonDto implements java.io.Serializable {

     private float valorMinimo;
     private float valorMaximo;

    public ValoresMedicionDto() {
    }

    
    public float getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(float valorMinimo) {
        this.valorMinimo = valorMinimo;
    }
    public float getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(float valorMaximo) {
        this.valorMaximo = valorMaximo;
    }

}


