package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

import java.util.Date;


/**
 * Rol generated by hbm2java
 */

public class VisitaDto extends CommonDto implements java.io.Serializable {

     private Integer idVisita;
     private String fechaVisita;
     private Float frecuencia;
     private int idPaciente;
     private int idUsuario;

    public VisitaDto() {
    }

    /**
     * @return the fechaVisita
     */
    public String getFechaVisita() {
        return fechaVisita;
    }

    /**
     * @param fechaVisita the fechaVisita to set
     */
    public void setFechaVisita(String fechaVisita) {
        this.fechaVisita = fechaVisita;
    }

    /**
     * @return the frecuencia
     */
    public Float getFrecuencia() {
        return frecuencia;
    }

    /**
     * @param frecuencia the frecuencia to set
     */
    public void setFrecuencia(Float frecuencia) {
        this.frecuencia = frecuencia;
    }

    /**
     * @return the idPaciente
     */
    public int getIdPaciente() {
        return idPaciente;
    }

    /**
     * @param idPaciente the idPaciente to set
     */
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }

    /**
     * @return the idUsuario
     */
    public int getIdUsuario() {
        return idUsuario;
    }

    /**
     * @param idUsuario the idUsuario to set
     */
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * @return the idVisita
     */
    public Integer getIdVisita() {
        return idVisita;
    }

    /**
     * @param idVisita the idVisita to set
     */
    public void setIdVisita(Integer idVisita) {
        this.idVisita = idVisita;
    }

	
}