package org.sim.services.entities.dtos;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;


/**
 * Rol generated by hbm2java
 */

public class VisitasDto extends CommonDto implements java.io.Serializable {

     private List<VisitaDto> visitas = new ArrayList<VisitaDto>(0);

    public VisitasDto() {
    }

    
    public List<VisitaDto> getVisitas() {
        return visitas;
    }

    /**
     * @param visitas the visitas to set
     */
    public void setVisitas(List<VisitaDto> visitas) {
        this.visitas = visitas;
    }

	
}