package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Administracionmedicamento generated by hbm2java
 */
@Entity
@Table(name="administracionmedicamento"
    ,catalog="sim2"
)
public class Administracionmedicamento  implements java.io.Serializable {


     private Integer idAdminMedic;
     private Libroreport libroreport;
     private Date fecha;
     private Float volumen;
     private String medicamento;
     private Float goteo;

    public Administracionmedicamento() {
    }

    public Administracionmedicamento(Libroreport libroreport, Date fecha, Float volumen, String medicamento, Float goteo) {
       this.libroreport = libroreport;
       this.fecha = fecha;
       this.volumen = volumen;
       this.medicamento = medicamento;
       this.goteo = goteo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAdminMedic", unique=true, nullable=false)
    public Integer getIdAdminMedic() {
        return this.idAdminMedic;
    }
    
    public void setIdAdminMedic(Integer idAdminMedic) {
        this.idAdminMedic = idAdminMedic;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public Libroreport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(Libroreport libroreport) {
        this.libroreport = libroreport;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="volumen", nullable=false, length=20)
    public Float getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(Float volumen) {
        this.volumen = volumen;
    }

    
    @Column(name="medicamento", nullable=false, length=50)
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }

    
    @Column(name="goteo", nullable=false, length=50)
    public Float getGoteo() {
        return this.goteo;
    }
    
    public void setGoteo(Float goteo) {
        this.goteo = goteo;
    }


}
