package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name="alerta"
    ,catalog="sim2"
)
public class Alerta  implements java.io.Serializable {


     private Integer idAlerta;
     private Libroreport libroreport;
     private Criticidad criticidad;
     private Date fecha;
     private Mensaje mensaje;

    public Alerta() {
    }

	
    public Alerta(Libroreport libroreport, Criticidad criticidad, Date fecha) {
        this.libroreport = libroreport;
        this.criticidad = criticidad;
        this.fecha = fecha;
    }
    public Alerta(Libroreport libroreport, Criticidad criticidad, Date fecha, Mensaje mensaje) {
       this.libroreport = libroreport;
       this.criticidad = criticidad;
       this.fecha = fecha;
       this.mensaje = mensaje;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAlerta", unique=true, nullable=false)
    public Integer getIdAlerta() {
        return this.idAlerta;
    }
    
    public void setIdAlerta(Integer idAlerta) {
        this.idAlerta = idAlerta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public Libroreport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(Libroreport libroreport) {
        this.libroreport = libroreport;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCriticidad", nullable=false)
    public Criticidad getCriticidad() {
        return this.criticidad;
    }
    
    public void setCriticidad(Criticidad criticidad) {
        this.criticidad = criticidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="alerta")
    public Mensaje getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(Mensaje mensaje) {
        this.mensaje = mensaje;
    }




}


