package org.sim.services.entities;
// Generated Oct 17, 2015 2:43:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Categoriarangoedad generated by hbm2java
 */
@Entity
@Table(name="categoriarangoedad"
    ,catalog="sim2"
)
public class Categoriarangoedad  implements java.io.Serializable {


     private int idCategoriaRangoEdad;
     private String descripcion;
     private int edadMinima;
     private int edadMaxima;
     private Valorestensionarterial valorestensionarterial;
     private Valorestemperatura valorestemperatura;
     private Valoresfrecuenciarespiratoria valoresfrecuenciarespiratoria;

    public Categoriarangoedad() {
    }

	
    public Categoriarangoedad(int idCategoriaRangoEdad, String descripcion, int edadMinima, int edadMaxima) {
        this.idCategoriaRangoEdad = idCategoriaRangoEdad;
        this.descripcion = descripcion;
        this.edadMinima = edadMinima;
        this.edadMaxima = edadMaxima;
    }
    public Categoriarangoedad(int idCategoriaRangoEdad, String descripcion, int edadMinima, int edadMaxima, Valorestensionarterial valorestensionarterial, Valorestemperatura valorestemperatura, Valoresfrecuenciarespiratoria valoresfrecuenciarespiratoria) {
       this.idCategoriaRangoEdad = idCategoriaRangoEdad;
       this.descripcion = descripcion;
       this.edadMinima = edadMinima;
       this.edadMaxima = edadMaxima;
       this.valorestensionarterial = valorestensionarterial;
       this.valorestemperatura = valorestemperatura;
       this.valoresfrecuenciarespiratoria = valoresfrecuenciarespiratoria;
    }
   
     @Id 

    
    @Column(name="idCategoriaRangoEdad", unique=true, nullable=false)
    public int getIdCategoriaRangoEdad() {
        return this.idCategoriaRangoEdad;
    }
    
    public void setIdCategoriaRangoEdad(int idCategoriaRangoEdad) {
        this.idCategoriaRangoEdad = idCategoriaRangoEdad;
    }

    
    @Column(name="descripcion", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="edadMinima", nullable=false)
    public int getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(int edadMinima) {
        this.edadMinima = edadMinima;
    }

    
    @Column(name="edadMaxima", nullable=false)
    public int getEdadMaxima() {
        return this.edadMaxima;
    }
    
    public void setEdadMaxima(int edadMaxima) {
        this.edadMaxima = edadMaxima;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="categoriarangoedad")
    public Valorestensionarterial getValorestensionarterial() {
        return this.valorestensionarterial;
    }
    
    public void setValorestensionarterial(Valorestensionarterial valorestensionarterial) {
        this.valorestensionarterial = valorestensionarterial;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="categoriarangoedad")
    public Valorestemperatura getValorestemperatura() {
        return this.valorestemperatura;
    }
    
    public void setValorestemperatura(Valorestemperatura valorestemperatura) {
        this.valorestemperatura = valorestemperatura;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="categoriarangoedad")
    public Valoresfrecuenciarespiratoria getValoresfrecuenciarespiratoria() {
        return this.valoresfrecuenciarespiratoria;
    }
    
    public void setValoresfrecuenciarespiratoria(Valoresfrecuenciarespiratoria valoresfrecuenciarespiratoria) {
        this.valoresfrecuenciarespiratoria = valoresfrecuenciarespiratoria;
    }




}


