package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Criticidad generated by hbm2java
 */
@Entity
@Table(name="Criticidad"
    ,catalog="sim2"
)
public class Criticidad  implements java.io.Serializable {


     private Integer idCriticidad;
     private String descripcion;
     

    public Criticidad() {
    }

	
    public Criticidad(int idCriticidad, String descripcion) {
        this.idCriticidad = idCriticidad;
        this.descripcion = descripcion;
    }
    
  
     @Id  
    @Column(name="idCriticidad", unique=true, nullable=false)
    public Integer getIdCriticidad() {
        return this.idCriticidad;
    }
    
    public void setIdCriticidad(Integer idCriticidad) {
        this.idCriticidad = idCriticidad;
    }


       
    @Column(name="descripcion", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

   
}


