package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ecg generated by hbm2java
 */
@Entity
@Table(name="ecg"
    ,catalog="sim2"
)
public class Ecg  implements java.io.Serializable {


     private Integer idEcg;
     private Libroreport libroreport;
     private String diagnostico;
     private String diagnosticoDetallado;
     private Date fecha;
     private String captura;
     private Float ppmMax;
     private Float ppmMin;
     private Float ppmProm;

    public Ecg() {
    }

	
    public Ecg(Libroreport libroreport, String diagnostico,String diagnosticoDettalado, Date fecha, Float ppmMax, Float ppmMin, Float ppmProm) {
        this.libroreport = libroreport;
        this.diagnostico = diagnostico;
        this.diagnosticoDetallado = diagnosticoDettalado;
        this.fecha = fecha;
        this.ppmMax = ppmMax;
        this.ppmMin = ppmMin;
        this.ppmProm = ppmProm;
    }
    
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idECG", unique=true, nullable=false)
    public Integer getIdEcg() {
        return this.idEcg;
    }
    
    public void setIdEcg(Integer idEcg) {
        this.idEcg = idEcg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public Libroreport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(Libroreport libroreport) {
        this.libroreport = libroreport;
    }

    
     @Column(name="diagnostico", length=100)
     public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    
    @Column(name="diagnosticoDetallado",  length=500)
    public String getDiagnosticoDetallado() {
        return this.diagnosticoDetallado;
    }
    
    public void setDiagnosticoDetallado(String diagnosticoDetallado) {
        this.diagnosticoDetallado = diagnosticoDetallado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

       
    @Column(name="captura")
   public String getCaptura() {
        return this.captura;
    }
    
    public void setCaptura(String captura) {
        this.captura = captura;
    }
    
    
    @Column(name="ppmMax", precision=12, scale=0)
    public Float getPpmMax() {
        return this.ppmMax;
    }
    
    public void setPpmMax(Float ppmMax) {
        this.ppmMax = ppmMax;
    }
@Column(name="ppmMin",  precision=12, scale=0)
    public Float getPpmMin() {
        return this.ppmMin;
    }
    
    public void setPpmMin(Float ppmMin) {
        this.ppmMin = ppmMin;
    }
    @Column(name="ppmProm",  precision=12, scale=0)
    public Float getPpmProm() {
        return this.ppmProm;
    }
    
    public void setPpmProm(Float ppmProm) {
        this.ppmProm = ppmProm;
    }



}


