package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Freceunciarespiratoria generated by hbm2java
 */
@Entity
@Table(name="freceunciarespiratoria"
    ,catalog="sim2"
)
@PrimaryKeyJoinColumn(name="idMedicion")
public class Freceunciarespiratoria  extends Medicion {

     private String freceunciaRespiratoria;

    public Freceunciarespiratoria() {
    }

    public Freceunciarespiratoria(String freceunciaRespiratoria) {
       this.freceunciaRespiratoria = freceunciaRespiratoria;
    }
   
    
    @Column(name="FreceunciaRespiratoria", nullable=false, length=20)
    public String getFreceunciaRespiratoria() {
        return this.freceunciaRespiratoria;
    }
    
    public void setFreceunciaRespiratoria(String freceunciaRespiratoria) {
        this.freceunciaRespiratoria = freceunciaRespiratoria;
    }




}


