package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Freceunciarespiratoria generated by hbm2java
 */
@Entity
@Table(name="freceunciarespiratoria"
    ,catalog="sim2"
)
public class Freceunciarespiratoria  implements java.io.Serializable {


     private int idMedicion;
     private String freceunciaRespiratoria;

    public Freceunciarespiratoria() {
    }

    public Freceunciarespiratoria(int idMedicion, String freceunciaRespiratoria) {
       this.idMedicion = idMedicion;
       this.freceunciaRespiratoria = freceunciaRespiratoria;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="FreceunciaRespiratoria", nullable=false, length=20)
    public String getFreceunciaRespiratoria() {
        return this.freceunciaRespiratoria;
    }
    
    public void setFreceunciaRespiratoria(String freceunciaRespiratoria) {
        this.freceunciaRespiratoria = freceunciaRespiratoria;
    }




}


