package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name="log"
    ,catalog="sim2"
)
public class Log  implements java.io.Serializable {


     private Integer idLog;
     private Date fecha;
     private int idUsuario;
     private int idAccion;

    public Log() {
    }

    public Log(Date fecha, int idUsuario, int idAccion) {
       this.fecha = fecha;
       this.idUsuario = idUsuario;
       this.idAccion = idAccion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idLog", unique=true, nullable=false)
    public Integer getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(Integer idLog) {
        this.idLog = idLog;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="idUsuario", nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="idAccion", nullable=false)
    public int getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(int idAccion) {
        this.idAccion = idAccion;
    }




}


