package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nivelglucosa generated by hbm2java
 */
@Entity
@Table(name="nivelglucosa"
    ,catalog="sim2"
)
public class Nivelglucosa  implements java.io.Serializable {


     private int idMedicion;
     private String glucosa;
     private String dosis;

    public Nivelglucosa() {
    }

    public Nivelglucosa(int idMedicion, String glucosa, String dosis) {
       this.idMedicion = idMedicion;
       this.glucosa = glucosa;
       this.dosis = dosis;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="Glucosa", nullable=false, length=20)
    public String getGlucosa() {
        return this.glucosa;
    }
    
    public void setGlucosa(String glucosa) {
        this.glucosa = glucosa;
    }

    
    @Column(name="Dosis", nullable=false, length=20)
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }




}


