package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="sim2"
    , uniqueConstraints = @UniqueConstraint(columnNames="DNI") 
)
public class Paciente  implements java.io.Serializable {


     private Integer idPaciente;
     private int dni;
     private String nombre;
     private String apellido;
     private int edad;
     private float altura;
     private float peso;
     private Libroreport libroreport;

    public Paciente() {
    }

	
    public Paciente(int dni, String nombre, String apellido, int edad, float altura, float peso) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.altura = altura;
        this.peso = peso;
    }
    public Paciente(int dni, String nombre, String apellido, int edad, float altura, float peso, Libroreport libroreport) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.altura = altura;
       this.peso = peso;
       this.libroreport = libroreport;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPaciente", unique=true, nullable=false)
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="DNI", unique=true, nullable=false)
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }

    
    @Column(name="Nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    
    @Column(name="Altura", nullable=false, precision=12, scale=0)
    public float getAltura() {
        return this.altura;
    }
    
    public void setAltura(float altura) {
        this.altura = altura;
    }

    
    @Column(name="Peso", nullable=false, precision=12, scale=0)
    public float getPeso() {
        return this.peso;
    }
    
    public void setPeso(float peso) {
        this.peso = peso;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="paciente")
    public Libroreport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(Libroreport libroreport) {
        this.libroreport = libroreport;
    }




}


