package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="sim2"
)
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Rolaccion> rolaccions = new HashSet<Rolaccion>(0);

    public Rol() {
    }

	
    public Rol(String nombreRol, int idRol) {
        this.nombreRol = nombreRol;
        this.idRol = idRol;
    }
    public Rol(String nombreRol, Set<Usuario> usuarios, Set<Rolaccion> rolaccions) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
       this.rolaccions = rolaccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    @Column(name="NombreRol", nullable=false, length=25)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Rolaccion> getRolaccions() {
        return this.rolaccions;
    }
    
    public void setRolaccions(Set<Rolaccion> rolaccions) {
        this.rolaccions = rolaccions;
    }




}


