package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Saturometria generated by hbm2java
 */
@Entity
@Table(name="saturometria"
    ,catalog="sim2"
)
@PrimaryKeyJoinColumn(name="idMedicion")
public class Saturometria extends Medicion {

     private float oxigenoEnSangre;

    public Saturometria() {
    }

    public Saturometria( float oxigenoEnSangre) {
       this.oxigenoEnSangre = oxigenoEnSangre;
    }
   
    
    @Column(name="OxigenoEnSangre", nullable=false, precision=12, scale=0)
    public float getOxigenoEnSangre() {
        return this.oxigenoEnSangre;
    }
    
    public void setOxigenoEnSangre(float oxigenoEnSangre) {
        this.oxigenoEnSangre = oxigenoEnSangre;
    }




}


