package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Tensionarterial generated by hbm2java
 */
@Entity
@Table(name="tensionarterial"
    ,catalog="sim2"
)
@PrimaryKeyJoinColumn(name="idMedicion")
public class Tensionarterial  extends Medicion {


     private Float tensionArterial;

    public Tensionarterial() {
    }

    public Tensionarterial(Float tensionArterial) {
       this.tensionArterial = tensionArterial;
    }
   
    
    @Column(name="TensionArterial", nullable=false, precision=12, scale=0)
    public float getTensionArterial() {
        return this.tensionArterial;
    }
    
    public void setTensionArterial(Float tensionArterial) {
        this.tensionArterial = tensionArterial;
    }




}


