package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tensionarterial generated by hbm2java
 */
@Entity
@Table(name="tensionarterial"
    ,catalog="sim2"
)
public class Tensionarterial  implements java.io.Serializable {


     private int idMedicion;
     private float tensionArterial;

    public Tensionarterial() {
    }

    public Tensionarterial(int idMedicion, float tensionArterial) {
       this.idMedicion = idMedicion;
       this.tensionArterial = tensionArterial;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="TensionArterial", nullable=false, precision=12, scale=0)
    public float getTensionArterial() {
        return this.tensionArterial;
    }
    
    public void setTensionArterial(float tensionArterial) {
        this.tensionArterial = tensionArterial;
    }




}


