package org.sim.services.entities;
// Generated Oct 17, 2015 2:43:20 PM by Hibernate Tools 4.3.1


import org.sim.services.entities.Categoriarangoedad;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Valorestensionarterial generated by hbm2java
 */
@Entity
@Table(name="valorestensionarterial"
    ,catalog="sim2"
)
public class Valorestensionarterial  implements java.io.Serializable {


     private int idValoresTensionArterial;
     private Categoriarangoedad categoriarangoedad;
     private int valorMaximo;
     private int valorMinimo;

    public Valorestensionarterial() {
    }

    public Valorestensionarterial(Categoriarangoedad categoriarangoedad, int valorMaximo, int valorMinimo) {
       this.categoriarangoedad = categoriarangoedad;
       this.valorMaximo = valorMaximo;
       this.valorMinimo = valorMinimo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="categoriarangoedad"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idValoresTensionArterial", unique=true, nullable=false)
    public int getIdValoresTensionArterial() {
        return this.idValoresTensionArterial;
    }
    
    public void setIdValoresTensionArterial(int idValoresTensionArterial) {
        this.idValoresTensionArterial = idValoresTensionArterial;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Categoriarangoedad getCategoriarangoedad() {
        return this.categoriarangoedad;
    }
    
    public void setCategoriarangoedad(Categoriarangoedad categoriarangoedad) {
        this.categoriarangoedad = categoriarangoedad;
    }

    
    @Column(name="valorMaximo", nullable=false)
    public int getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(int valorMaximo) {
        this.valorMaximo = valorMaximo;
    }

    
    @Column(name="valorMinimo", nullable=false)
    public int getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(int valorMinimo) {
        this.valorMinimo = valorMinimo;
    }




}


