package org.sim.services.entities;
// Generated Oct 17, 2015 2:43:20 PM by Hibernate Tools 4.3.1


import org.sim.services.entities.Categoriarangoedad;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Valorestemperatura generated by hbm2java
 */
@Entity
@Table(name="valorestemperatura"
    ,catalog="sim2"
)
public class Valorestemperatura  implements java.io.Serializable {


     private int idValoresTemperatura;
     private Categoriarangoedad categoriarangoedad;
     private float valorMinimo;
     private float valorMaximo;

    public Valorestemperatura() {
    }

    public Valorestemperatura(Categoriarangoedad categoriarangoedad, float valorMinimo, float valorMaximo) {
       this.categoriarangoedad = categoriarangoedad;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="categoriarangoedad"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idValoresTemperatura", unique=true, nullable=false)
    public int getIdValoresTemperatura() {
        return this.idValoresTemperatura;
    }
    
    public void setIdValoresTemperatura(int idValoresTemperatura) {
        this.idValoresTemperatura = idValoresTemperatura;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Categoriarangoedad getCategoriarangoedad() {
        return this.categoriarangoedad;
    }
    
    public void setCategoriarangoedad(Categoriarangoedad categoriarangoedad) {
        this.categoriarangoedad = categoriarangoedad;
    }

    
    @Column(name="valorMinimo", nullable=false, precision=5, scale=1)
    public float getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(float valorMinimo) {
        this.valorMinimo = valorMinimo;
    }

    
    @Column(name="valorMaximo", nullable=false, precision=5, scale=1)
    public float getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(float valorMaximo) {
        this.valorMaximo = valorMaximo;
    }




}


