package org.sim.services.entities;
// Generated Oct 17, 2015 2:43:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Valoresfrecuenciarespiratoria generated by hbm2java
 */
@Entity
@Table(name="valoresfrecuenciarespiratoria"
    ,catalog="sim2"
)
public class Valoresfrecuenciarespiratoria  implements java.io.Serializable {


     private int idValoresFrecuenciaRespiratoria;
     private Categoriarangoedad categoriarangoedad;
     private int valorMinimo;
     private int valorMaximo;

    public Valoresfrecuenciarespiratoria() {
    }

    public Valoresfrecuenciarespiratoria(Categoriarangoedad categoriarangoedad, int valorMinimo, int valorMaximo) {
       this.categoriarangoedad = categoriarangoedad;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="categoriarangoedad"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idValoresFrecuenciaRespiratoria", unique=true, nullable=false)
    public int getIdValoresFrecuenciaRespiratoria() {
        return this.idValoresFrecuenciaRespiratoria;
    }
    
    public void setIdValoresFrecuenciaRespiratoria(int idValoresFrecuenciaRespiratoria) {
        this.idValoresFrecuenciaRespiratoria = idValoresFrecuenciaRespiratoria;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Categoriarangoedad getCategoriarangoedad() {
        return this.categoriarangoedad;
    }
    
    public void setCategoriarangoedad(Categoriarangoedad categoriarangoedad) {
        this.categoriarangoedad = categoriarangoedad;
    }

    
    @Column(name="ValorMinimo", nullable=false)
    public int getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(int valorMinimo) {
        this.valorMinimo = valorMinimo;
    }

    
    @Column(name="ValorMaximo", nullable=false)
    public int getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(int valorMaximo) {
        this.valorMaximo = valorMaximo;
    }




}


