package org.sim.services.entities;
// Generated Aug 22, 2015 1:16:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visita generated by hbm2java
 */
@Entity
@Table(name="visita"
    ,catalog="sim2"
)
public class Visita  implements java.io.Serializable {


     private Integer idVisita;
     private Date fechaVisita;
     private Usuario usuario;
     private Paciente paciente;

    public Visita() {
    }

	
    public Visita(Date fechaVisita) {
        this.fechaVisita = fechaVisita;
    }
    
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVisita", unique=true, nullable=false)
    public Integer getIdVisita() {
        return this.idVisita;
    }
    
    public void setIdVisita(Integer idVisita) {
        this.idVisita = idVisita;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaVisita", nullable=false, length=10)
    public Date getFechaVisita() {
        return this.fechaVisita;
    }
    
    public void setFechaVisita(Date fechaVisita) {
        this.fechaVisita = fechaVisita;
    }


    /**
     * @return the usuario
     */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

   @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPaciente", nullable=false)
    public Paciente getPaciente() {
        return paciente;
    }

    /**
     * @param paciente the paciente to set
     */
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }




}


